### ISSUE TITLE
Syntax error in config file kills Astrid

### ISSUE THREAD

**Issue by LukasLedvina** [fykosak/astrid#4]
Syntax error in `.astrid/config.ini` in section `tools.auth_basic.checkpassword:` missing comma between users kills Astrid. Example:

```
tools.auth_basic.checkpassword: cherrypy.lib.auth_basic.checkpassword_dict({
        'user1': 'pass1'
        'user2': 'pass2'
        })
```

**Comment by Werkov** [comment]
It still kills Astrid, however, it should [recover](https://github.com/fykosak/astrid/blob/master/astrid.service#L9-L11), if you fix it. (It should attempt restart every 10 seconds.)

Please close (or reassign) upon verification. Thanks.
